package io.github.mrtnha.librifin

import android.app.Application
import io.github.mrtnha.librifin.platform.AndroidPlatform

/** Holds the [AppServices] for the whole process, so they outlive the activity (see [AppServices]). */
class LibrifinApplication : Application() {
    val services by lazy {
        AppServices(
            AndroidPlatform(this) {
                // Generated by the AboutLibraries plugin at build time
                resources.openRawResource(R.raw.aboutlibraries).bufferedReader().use { it.readText() }
            },
        )
    }
}
